services:

  ow2-replaycode-ocr:
    build:
      context: .
    container_name: ow2-replaycode-ocr
    volumes:
      - ./output:/app/output
      - ./model-data:/app/model-data
    stdin_open: true
    tty: true
    #restart: unless-stopped
